services:
  - type: web
    name: ceshi-backend
    env: node
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start

  - type: static
    name: ceshi-frontend
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
